### ISSUE TITLE
[ EPIC ] Developer Documentation

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/developer-portal#61]
As a developer/integrator, I need good documentation and a clear getting started guide for using the SDK and all the tools that Vocdoni offers to me. 

**Write new docs**

From getting started section:

- [ ] Create the "Getting Started Guide" (now we are using the SDK readme, maybe can be this?)
- [ ] Add UI-Components docs
- [ ] FAQs

Tutorials (inside getting started):

- [ ] Create your first election
- [ ] Create your first quadratic voting
- [ ] How to configure the lifecycle of an election
- [ ] Census types and how to create them
- [ ] Retrieving elections results
- [ ] Vote in an election

Protocol (inside Reference):

- [ ] Encryption and validators
- [ ] Faucet package
- [ ] Transactions
- [ ] Results
- [ ] Accounts and organizations
- [ ] Libraries and tooling

Vochain (inside Reference):

- [ ] Run a node
- [ ] Deployed networks
- [ ] ...?

**Old Docs:**
- [x] Retrieve and propose what we can reuse from docs.vocdoni.io
- [x] Merge the 2 docs in 1
- [ ] Redirect docs.vocdoni.io to developer.vocdoni.io

**More tasks:**

- [ ] Plausible events for new sections
- [x] Add SDK changelog into the Developer Portal

More references: https://www.notion.so/aragonorg/Developer-Portal-a8c15bc54bcb4e759fc8eda248c7afe3

**Comment by selankon** [comment]
I added a tasks  `Plausible events for new sections` to the backlog

**Comment by selankon** [comment]
Changelog marked as resolved

https://github.com/vocdoni/developer-portal/pull/68
https://github.com/vocdoni/vocdoni-sdk/pull/162

**Comment by selankon** [comment]
`Merge the 2 docs in 1` task will be completed after 

https://github.com/vocdoni/developer-portal/pull/69
